### ISSUE TITLE
Phantom JS installation fails

### ISSUE THREAD

**Issue by bartveenstra** [Backbase/bb-lp-cli#15]
In a locked down environment the installation of phantomjs fails:

`> phantomjs@1.9.20 install /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/ADOP_NodeJS/lib/node_modules/bb-lp-cli/node_modules/phantomjs

> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:484:12)`
```

There is no control to the server or possibility to install the required libraries. 

Please remove phantomjs as a required dependency for the bb-lp-cli

**Comment by dragosh** [comment]
We need to test on Linux dist. as well @bartveenstra before removing the phantomjs, is it required for tests, we cant just remove it. Maybe is related with this https://github.com/Medium/phantomjs/pull/468.
I'll make some time to test it on Linux dist. can you provide me what Linux distribution did you try it installing the CLI? thanks.

**Comment by sorohan** [comment]
Looks like it's failing from not having bzip2 available. Looks more like this one:
https://github.com/Medium/phantomjs/issues/92

@bartveenstra can you try installing bzip2?

**Comment by dragosh** [comment]
@sorohan you're right. @bartveenstra can you check to see if `which bzip2`? if not maybe install it and check again, if you can't install it on the machine, we need to find a different solution; maybe have phantomjs zip file already in the CLI and unzip with the default OS unarchiver. (tar, zip)

**Comment by bartveenstra** [comment]
We have created a jenkins build slave with SSH access so we could add bzip2. installation succeeded but we ran into issues with building widgets. On the fork I strippped away most of it to identify the issue for building, and it seems that the gulp notify might be the issue. I was racing against a clock, so I left it using the fork. Need to try the original one to check of the gulp notify is the culprit and create a PR
