### ISSUE TITLE
Windows 7 - Installation exception

### ISSUE THREAD

**Issue by aahad** [Backbase/bb-lp-cli#19]
I have tried many times to install "bb-lp-cli" but it is not getting installed successfully. However "bb-cli" got installed successfully.

I tried (1) by running cmd as administrator , (2) tried by disabling antivirus, (3) tried using "--force" flag, (4) tried by "npm cache clean" but it did not work all the times. 

I am getting following error all the times.

```
C:\backbase\CLI\bb-lp-cli-master>npm install -g bb-lp-cli
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls gracef
ul-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated promise.prototype.finally@1.0.1: Please upgrade to v2.0 or higher!
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench fo
r. Thanks for all the usage over the years.
npm WARN deprecated nunjucks@1.3.4: potential XSS vulnerability in autoescape mode, and with escape filter was fixed in v2.4.3
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls gracef
ul-fs' to find it in the tree.
npm WARN deprecated nunjucks@2.2.0: potential XSS vulnerability in autoescape mode, and with escape filter was fixed in v2.4.3
C:\Users\IBM_ADMIN\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\bb-lp-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~0.3.1 (node_modules\bb-lp-cli\node_modules\nunjucks\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bb-lp-cli"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\bb-lp-cli
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\bb-lp-cli' -> 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\.bb-l
p-cli.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\bb-lp-cli' -> 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\.bb-l
p-cli.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\bb-lp-cli' -> 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\.bb-
lp-cli.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\bb-lp-cli' -> 'C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\.bb-l
p-cli.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\backbase\CLI\bb-lp-cli-master\npm-debug.log
npm ERR! code 1


```

**Comment by craigwalkeruk** [comment]
Please read the Windows section regarding installation of sime dependencies.

https://github.com/Backbase/bb-lp-cli/blob/master/README.md#important-notes

**Comment by aahad** [comment]
I re-verified the dependencies present on my machine. I have;

(1) Python v2.7.3 
(2) Microsoft Visual Studio C++2015
(3) Windows 7 64-bit SDK

My W**indows 7 64-bit SDK** path contains **v7.0A , v7.1A , v8.1 , v8.1A**

the **bin** folder inside  v7.0A , v7.1A does not contain "**Setenv.cmd**" file.

**Comment by aahad** [comment]
I just tried to change the npm cache location from"users" folder to another place. But it did not help either.

**Comment by dragosh** [comment]
Hi @aahad thanks for the details provided , i have a question before diving into the problem.
why you are trying to install the package from the same location where you cloned it? 
Can you try install it from another location, and before doing that please delete the cache manually, i know on windows npm cache clean doesn't work `C:\Users\username\AppData\Roaming\npm-cache`

**Comment by aahad** [comment]
Yes I had tried from other locations multiple times. And when it did not work then I tried to download package and from within that directory I tried.

The npm cache clean is working fine. I see it deletes all stuff within that folder.

**Comment by aahad** [comment]
I just tried it on Docker Centos latest image. There it got installed but then it given other issues when executing the command ( "bblp --help or bblp --version or bblp " )

I am not putting those details in this thread, just keeping it focused on the windows 7 machine only.

**Comment by dragosh** [comment]
@aahad do you still have this issue?

**Comment by aahad** [comment]
Yes still issue.

**Comment by dragosh** [comment]
@aahad you don't need to download the package, and install it within the same directory (this will fail for sure). i would suggest to uninstall your nodejs and node_modules from previous installations and use a nodejs version manager https://github.com/coreybutler/nvm-windows. 

Let me know if you encounter the same problem or different on.

**Comment by aahad** [comment]
@dragosh I had one time only downloaded package and tried installing inside it when normal installation command/process was not working. Let me try to install NVM and check it out how it goes.
