### ISSUE TITLE
bblp test windows karma-webpack error

### ISSUE THREAD

**Issue by dragosh** [Backbase/bb-lp-cli#20]
```
31 10 2016 15:54:15.673:ERROR [karma]: { [Error: invalid argument]
  code: 'EINVAL',
  errno: 18,
  message: 'invalid argument',
  path: '../sandbox/dev/onboarding-collection/widget/siema/test/unit/index.js' }
Error: invalid argument
    at pathToArray (c:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:51:19)
    at MemoryFileSystem.readFileSync (c:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:114:16)
    at MemoryFileSystem.readFile (c:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:309:27)
    at doRead (c:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\index.js:159:35)
    at Plugin.readFile (c:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\index.js:166:3)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)
? Something went wrong while running the tests: exit code 1

I have found how to fix bblp test runner, you need to edit file
C:\Users\43997483\AppData\Roaming\npm\node_modules\bb-lp-cli\node_modules\karma-webpack\index.js:157
 
Change code 
var kwFile = path.join('', file).replace(/\\/g, "/");
 
to
var kwFile = path.join('/', file).replace(/\\/g, "/");
```

**Comment by dragosh** [comment]
there is a fix committed here https://github.com/dragosh/karma-webpack/commit/38bd05bf3096c8b55cc8703087ae8836db04aa7e

So basically need to reinstall the package again. 

if the bower_components is not in the widget folder you can use the `--moduleDirectories` param

`bblp test --moduleDirectories ../path/to/my/bower_components`
